# Generated by Django 3.2.9 on 2021-11-24 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vider',
            new_name='Video',
        ),
    ]
